### ISSUE TITLE
Cant redeploy same files 

### ISSUE THREAD

**Issue by povils** [capistrano-s3/capistrano-s3#46]
So if i create a new static file and deploy it to s3 -  it works.
But if I do cap stage deploy again it does nothing. When I delete the file and create with the same name it works again.

**Comment by hoangmy92** [comment]
This plugin manages file's stage and skips the existed file.
You could check the above method for more information
https://github.com/capistrano-s3/capistrano-s3/blob/master/lib/capistrano/s3/publisher.rb#L18

Also, take a look at **.last_invalidation** and **.last_published** on the deployment's root directory

**Comment by aleksandrs-ledovskis** [comment]
As correctly noted by @hoangmy92, this library tries not to do unnecessary AWS S3 uploads by comparing publishable file timestamps with `.last_*` records.

Deletion of files is to-be-developed (tracked in https://github.com/capistrano-s3/capistrano-s3/issues/9)
