### ISSUE TITLE
undefined method `namespace'

### ISSUE THREAD

**Issue by deep0389** [capistrano-s3/capistrano-s3#51]
Getting this error while trying to use after install.

.rvm/gems/ruby-2.4.1/gems/capistrano-s3-2.3.0/lib/capistrano/tasks/capistrano_3.rb:1:in `<main>': undefined method `namespace' for main:Object (NoMethodError)

Capistrano version - 3.11.0

**Comment by aleksandrs-ledovskis** [comment]
Is Rake loaded and required in your code? 

Here's similar issue (by looks of it) - https://github.com/resque/resque-scheduler/issues/472#issuecomment-172209007
